# Generated by Django 5.2.7 on 2026-02-11 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Rasm')),
                ('image_alt_uz', models.CharField(blank=True, max_length=255, verbose_name="Rasm alt (O'zbekcha)")),
                ('image_alt_ru', models.CharField(blank=True, max_length=255, verbose_name='Rasm alt (Ruscha)')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='Rasm alt (Inglizcha)')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Qisqa tavsif')),
                ('event_date', models.DateField(verbose_name='Tadbir sanasi')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name="Narxi (so'm)")),
                ('is_free', models.BooleanField(default=False, verbose_name='Bepulmi?')),
                ('total_slots', models.PositiveIntegerField(default=0, verbose_name="Jami o'rinlar soni")),
                ('booked_slots', models.PositiveIntegerField(default=0, verbose_name="Band qilingan o'rinlar")),
                ('button_text', models.CharField(default="Ro'yxatdan o'tish", max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(blank=True, max_length=255, verbose_name='Tugma havolasi')),
                ('venue_name', models.CharField(blank=True, max_length=255, verbose_name='Joy nomi')),
                ('venue_address', models.TextField(blank=True, verbose_name='Manzil')),
                ('venue_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon raqami')),
                ('venue_website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('venue_map_embed', models.TextField(blank=True, verbose_name='Google Maps iframe kodi')),
                ('facebook_link', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_link', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Telegram')),
                ('youtube_link', models.URLField(blank=True, verbose_name='YouTube')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tanlangan')),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='events.event', verbose_name='Tadbir')),
            ],
            options={
                'verbose_name': 'Tadbir xususiyati',
                'verbose_name_plural': 'Tadbir xususiyatlari',
                'ordering': ['order', 'title'],
            },
        ),
    ]
