# Generated by Django 5.2.7 on 2026-02-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='button_text_en',
            field=models.CharField(default="Ro'yxatdan o'tish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='event',
            name='button_text_ru',
            field=models.CharField(default="Ro'yxatdan o'tish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='event',
            name='button_text_uz',
            field=models.CharField(default="Ro'yxatdan o'tish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_address_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_address_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Joy nomi'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Joy nomi'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Joy nomi'),
        ),
        migrations.AddField(
            model_name='eventfeature',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='eventfeature',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='eventfeature',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='eventfeature',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='eventfeature',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='eventfeature',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
