# Generated by Django 5.2.7 on 2026-02-17 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(upload_to='news/images/', verbose_name='Rasm')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt matn')),
                ('alt_text_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt matn')),
                ('alt_text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt matn')),
                ('alt_text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt matn')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Yangilik rasmi',
                'verbose_name_plural': 'Yangilik rasmlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Rasm')),
                ('image_alt_uz', models.CharField(blank=True, max_length=255, verbose_name="Rasm alt (O'zbekcha)")),
                ('image_alt_ru', models.CharField(blank=True, max_length=255, verbose_name='Rasm alt (Ruscha)')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='Rasm alt (Inglizcha)')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Qisqa tavsif')),
                ('short_description_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Qisqa tavsif')),
                ('short_description_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Qisqa tavsif')),
                ('short_description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Qisqa tavsif')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('content_uz', models.TextField(null=True, verbose_name='Kontent')),
                ('content_ru', models.TextField(null=True, verbose_name='Kontent')),
                ('content_en', models.TextField(null=True, verbose_name='Kontent')),
                ('published_at', models.DateTimeField(verbose_name='Nashr sanasi')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tanlangan')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.newscategory', verbose_name='Kategoriya')),
                ('images', models.ManyToManyField(blank=True, related_name='news', to='news.newsimage', verbose_name="Qo'shimcha rasmlar")),
                ('tags', models.ManyToManyField(blank=True, related_name='news', to='news.newstag', verbose_name='Teglar')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holati')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news', verbose_name='Yangilik')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
