# Generated by Django 5.2.7 on 2026-02-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Nashr sanasi'),
        ),
    ]
