# Generated by Django 5.2.7 on 2026-02-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Rasm')),
                ('image_alt_uz', models.CharField(blank=True, max_length=255, verbose_name="Rasm alt (O'zbekcha)")),
                ('image_alt_ru', models.CharField(blank=True, max_length=255, verbose_name='Rasm alt (Ruscha)')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='Rasm alt (Inglizcha)')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('full_name_uz', models.CharField(max_length=255, null=True, verbose_name='F.I.O')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='F.I.O')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='F.I.O')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('position_uz', models.CharField(max_length=255, null=True, verbose_name='Lavozim')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Lavozim')),
                ('position_en', models.CharField(max_length=255, null=True, verbose_name='Lavozim')),
                ('degree', models.CharField(blank=True, max_length=255, verbose_name='Ilmiy daraja')),
                ('degree_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy daraja')),
                ('degree_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy daraja')),
                ('degree_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy daraja')),
                ('short_bio', models.TextField(verbose_name="Qisqa ma'lumot")),
                ('short_bio_uz', models.TextField(null=True, verbose_name="Qisqa ma'lumot")),
                ('short_bio_ru', models.TextField(null=True, verbose_name="Qisqa ma'lumot")),
                ('short_bio_en', models.TextField(null=True, verbose_name="Qisqa ma'lumot")),
                ('biography', models.TextField(blank=True, verbose_name='Biografiya')),
                ('biography_uz', models.TextField(blank=True, null=True, verbose_name='Biografiya')),
                ('biography_ru', models.TextField(blank=True, null=True, verbose_name='Biografiya')),
                ('biography_en', models.TextField(blank=True, null=True, verbose_name='Biografiya')),
                ('education', models.TextField(blank=True, verbose_name="Ma'lumoti")),
                ('education_uz', models.TextField(blank=True, null=True, verbose_name="Ma'lumoti")),
                ('education_ru', models.TextField(blank=True, null=True, verbose_name="Ma'lumoti")),
                ('education_en', models.TextField(blank=True, null=True, verbose_name="Ma'lumoti")),
                ('expertise', models.TextField(blank=True, verbose_name='Mutaxassislik sohalari')),
                ('expertise_uz', models.TextField(blank=True, null=True, verbose_name='Mutaxassislik sohalari')),
                ('expertise_ru', models.TextField(blank=True, null=True, verbose_name='Mutaxassislik sohalari')),
                ('expertise_en', models.TextField(blank=True, null=True, verbose_name='Mutaxassislik sohalari')),
                ('courses', models.TextField(blank=True, verbose_name='Darslar')),
                ('courses_uz', models.TextField(blank=True, null=True, verbose_name='Darslar')),
                ('courses_ru', models.TextField(blank=True, null=True, verbose_name='Darslar')),
                ('courses_en', models.TextField(blank=True, null=True, verbose_name='Darslar')),
                ('publications', models.TextField(blank=True, verbose_name='Ilmiy nashrlari')),
                ('publications_uz', models.TextField(blank=True, null=True, verbose_name='Ilmiy nashrlari')),
                ('publications_ru', models.TextField(blank=True, null=True, verbose_name='Ilmiy nashrlari')),
                ('publications_en', models.TextField(blank=True, null=True, verbose_name='Ilmiy nashrlari')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('reception_days', models.CharField(blank=True, max_length=255, verbose_name='Qabul kunlari')),
                ('reception_days_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qabul kunlari')),
                ('reception_days_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qabul kunlari')),
                ('reception_days_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qabul kunlari')),
                ('facebook_link', models.URLField(blank=True, verbose_name='Facebook')),
                ('linkedin_link', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Telegram')),
                ('youtube_link', models.URLField(blank=True, verbose_name='YouTube')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Rahbar',
                'verbose_name_plural': 'Rahbariyat',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
