# Generated by Django 5.2.7 on 2026-02-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=100, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Sarlavha')),
                ('description', models.CharField(max_length=255, verbose_name='Tavsif')),
                ('description_uz', models.CharField(max_length=255, null=True, verbose_name='Tavsif')),
                ('description_ru', models.CharField(max_length=255, null=True, verbose_name='Tavsif')),
                ('description_en', models.CharField(max_length=255, null=True, verbose_name='Tavsif')),
                ('link', models.CharField(max_length=255, verbose_name='Havola')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Banner Navigatsiya',
                'verbose_name_plural': 'Banner Navigatsiyalar',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BannerSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Rasm')),
                ('image_alt_uz', models.CharField(blank=True, max_length=255, verbose_name="Rasm alt (O'zbekcha)")),
                ('image_alt_ru', models.CharField(blank=True, max_length=255, verbose_name='Rasm alt (Ruscha)')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='Rasm alt (Inglizcha)')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name="Qo'shimcha sarlavha")),
                ('subtitle_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name="Qo'shimcha sarlavha")),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name="Qo'shimcha sarlavha")),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True, verbose_name="Qo'shimcha sarlavha")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Tugma matni')),
                ('button_text_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_text_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_text_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_link', models.CharField(blank=True, max_length=255, verbose_name='Tugma havolasi')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL (YouTube/Vimeo)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Banner Slider',
                'verbose_name_plural': 'Banner Sliderlar',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
