# Generated by Django 5.2.7 on 2026-02-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('show_video', models.BooleanField(default=False, verbose_name="Video ko'rsatish")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Banner sozlamasi',
                'verbose_name_plural': 'Banner sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='BannerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name="Qo'shimcha sarlavha")),
                ('video_file', models.FileField(upload_to='banners/videos/', verbose_name='Video fayl (MP4)')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='banners/posters/', verbose_name='Poster rasm')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(blank=True, max_length=255, verbose_name='Tugma havolasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Banner Video',
                'verbose_name_plural': 'Banner Videolar',
            },
        ),
        migrations.RemoveField(
            model_name='bannerslider',
            name='video_url',
        ),
    ]
