# Generated by Django 5.2.7 on 2026-02-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bannersettings_bannervideo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Rasm')),
                ('image_alt_uz', models.CharField(blank=True, max_length=255, verbose_name="Rasm alt (O'zbekcha)")),
                ('image_alt_ru', models.CharField(blank=True, max_length=255, verbose_name='Rasm alt (Ruscha)')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='Rasm alt (Inglizcha)')),
                ('subtitle', models.CharField(max_length=255, verbose_name="Qo'shimcha sarlavha")),
                ('subtitle_uz', models.CharField(max_length=255, null=True, verbose_name="Qo'shimcha sarlavha")),
                ('subtitle_ru', models.CharField(max_length=255, null=True, verbose_name="Qo'shimcha sarlavha")),
                ('subtitle_en', models.CharField(max_length=255, null=True, verbose_name="Qo'shimcha sarlavha")),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('description_uz', models.TextField(null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(null=True, verbose_name='Tavsif')),
                ('description_2', models.TextField(blank=True, verbose_name='Tavsif 2')),
                ('description_2_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif 2')),
                ('description_2_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif 2')),
                ('description_2_en', models.TextField(blank=True, null=True, verbose_name='Tavsif 2')),
                ('left_image_1', models.ImageField(upload_to='about/', verbose_name='Chap rasm 1')),
                ('left_image_2', models.ImageField(upload_to='about/', verbose_name='Chap rasm 2')),
                ('circle_text', models.CharField(max_length=255, verbose_name='Aylanuvchi matn')),
                ('circle_text_uz', models.CharField(max_length=255, null=True, verbose_name='Aylanuvchi matn')),
                ('circle_text_ru', models.CharField(max_length=255, null=True, verbose_name='Aylanuvchi matn')),
                ('circle_text_en', models.CharField(max_length=255, null=True, verbose_name='Aylanuvchi matn')),
                ('mission_title', models.CharField(max_length=100, verbose_name='Missiya sarlavhasi')),
                ('mission_title_uz', models.CharField(max_length=100, null=True, verbose_name='Missiya sarlavhasi')),
                ('mission_title_ru', models.CharField(max_length=100, null=True, verbose_name='Missiya sarlavhasi')),
                ('mission_title_en', models.CharField(max_length=100, null=True, verbose_name='Missiya sarlavhasi')),
                ('mission_icon', models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Missiya icon')),
                ('vision_title', models.CharField(max_length=100, verbose_name='Viziya sarlavhasi')),
                ('vision_title_uz', models.CharField(max_length=100, null=True, verbose_name='Viziya sarlavhasi')),
                ('vision_title_ru', models.CharField(max_length=100, null=True, verbose_name='Viziya sarlavhasi')),
                ('vision_title_en', models.CharField(max_length=100, null=True, verbose_name='Viziya sarlavhasi')),
                ('vision_icon', models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Viziya icon')),
                ('button_text', models.CharField(max_length=100, verbose_name='Tugma matni')),
                ('button_text_uz', models.CharField(max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_text_ru', models.CharField(max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_text_en', models.CharField(max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_link', models.CharField(max_length=255, verbose_name='Tugma havolasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Universitet haqida section',
                'verbose_name_plural': 'Universitet haqida sections',
            },
        ),
        migrations.AddField(
            model_name='bannervideo',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='bannervideo',
            name='button_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='bannervideo',
            name='button_text_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='bannervideo',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Qo'shimcha sarlavha"),
        ),
        migrations.AddField(
            model_name='bannervideo',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Qo'shimcha sarlavha"),
        ),
        migrations.AddField(
            model_name='bannervideo',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Qo'shimcha sarlavha"),
        ),
        migrations.AddField(
            model_name='bannervideo',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='bannervideo',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='bannervideo',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
