# Generated by Django 5.2.7 on 2026-02-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutsection_bannervideo_button_text_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': '2. Universitet haqida', 'verbose_name_plural': '2. Universitet haqida'},
        ),
        migrations.AlterModelOptions(
            name='bannernavigation',
            options={'ordering': ['order', 'title'], 'verbose_name': '1. Banner Navigatsiya', 'verbose_name_plural': '1. Banner Navigatsiyalar'},
        ),
        migrations.AlterModelOptions(
            name='bannersettings',
            options={'verbose_name': '1. Banner sozlamasi', 'verbose_name_plural': '1. Banner sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='bannerslider',
            options={'ordering': ['order', '-created_at'], 'verbose_name': '1. Banner Slider', 'verbose_name_plural': '1. Banner Sliderlar'},
        ),
        migrations.AlterModelOptions(
            name='bannervideo',
            options={'verbose_name': '1. Banner Video', 'verbose_name_plural': '1. Banner Videolar'},
        ),
    ]
