# Generated by Django 5.2.7 on 2026-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_aboutsection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha (90%, Top 10, №1)')),
                ('description', models.CharField(max_length=255, verbose_name='Tavsif')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Statistika elementi',
                'verbose_name_plural': 'Statistika elementlari',
                'ordering': ['order', 'title'],
            },
        ),
    ]
