# Generated by Django 5.2.7 on 2026-02-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_statisticitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticitem',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='statisticitem',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='statisticitem',
            name='description_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Tavsif'),
        ),
    ]
