# Generated by Django 5.2.7 on 2026-02-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_statisticitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statisticitem',
            options={'ordering': ['order', 'title'], 'verbose_name': '3. Statistika bloki', 'verbose_name_plural': '3. Statistika bloki'},
        ),
    ]
