# Generated by Django 5.2.7 on 2026-02-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_statisticitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStaticTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(default="So'nggi yangiliklar", max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('button_text', models.CharField(default="Barchasini ko'rish", max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='/news/', max_length=255, verbose_name='Tugma havolasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': '4. Yangiliklar statik matnlari',
                'verbose_name_plural': '4. Yangiliklar statik matnlari',
            },
        ),
    ]
