# Generated by Django 5.2.7 on 2026-02-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_newsstatictexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstatictexts',
            name='button_text_en',
            field=models.CharField(default="Barchasini ko'rish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='button_text_ru',
            field=models.CharField(default="Barchasini ko'rish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='button_text_uz',
            field=models.CharField(default="Barchasini ko'rish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='title_en',
            field=models.CharField(default="So'nggi yangiliklar", max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='title_ru',
            field=models.CharField(default="So'nggi yangiliklar", max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='title_uz',
            field=models.CharField(default="So'nggi yangiliklar", max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
