# Generated by Django 5.2.7 on 2026-02-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_newsstatictexts_button_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('logo', models.FileField(upload_to='partners/', verbose_name='Logotip (SVG/PNG)')),
                ('link', models.URLField(blank=True, verbose_name='Veb-sayt havolasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': '5. Hamkor',
                'verbose_name_plural': '5. Hamkorlar',
                'ordering': ['order', 'name'],
            },
        ),
    ]
