# Generated by Django 5.2.7 on 2026-02-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
    ]
