# Generated by Django 5.2.7 on 2026-02-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_partner_name_en_partner_name_ru_partner_name_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('background_image', models.ImageField(upload_to='licenses/', verbose_name='Fon rasmi')),
                ('button_text', models.CharField(default="Ko'rish", max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='#', max_length=255, verbose_name='Tugma havolasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': '6. Litsenziya elementi',
                'verbose_name_plural': '6. Litsenziya elementlari',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseStaticTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(default='Litsenziya va Akkreditatsiya', max_length=255, verbose_name='Sarlavha')),
                ('button_text', models.CharField(default='Batafsil', max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='#', max_length=255, verbose_name='Tugma havolasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': '6. Litsenziya statik matnlari',
                'verbose_name_plural': '6. Litsenziya statik matnlari',
            },
        ),
    ]
