# Generated by Django 5.2.7 on 2026-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_licenseitem_licensestatictexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseitem',
            name='button_text_en',
            field=models.CharField(default="Ko'rish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='licenseitem',
            name='button_text_ru',
            field=models.CharField(default="Ko'rish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='licenseitem',
            name='button_text_uz',
            field=models.CharField(default="Ko'rish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='licenseitem',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='licenseitem',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='licenseitem',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='licenseitem',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='licenseitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='licenseitem',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='licensestatictexts',
            name='button_text_en',
            field=models.CharField(default='Batafsil', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='licensestatictexts',
            name='button_text_ru',
            field=models.CharField(default='Batafsil', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='licensestatictexts',
            name='button_text_uz',
            field=models.CharField(default='Batafsil', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='licensestatictexts',
            name='title_en',
            field=models.CharField(default='Litsenziya va Akkreditatsiya', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='licensestatictexts',
            name='title_ru',
            field=models.CharField(default='Litsenziya va Akkreditatsiya', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='licensestatictexts',
            name='title_uz',
            field=models.CharField(default='Litsenziya va Akkreditatsiya', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
