# Generated by Django 5.2.7 on 2026-02-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_licenseitem_button_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStaticTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(default="Ta'lim dasturlari", max_length=255, verbose_name='Sarlavha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': "7. Ta'lim dasturlari statik matnlari",
                'verbose_name_plural': "7. Ta'lim dasturlari statik matnlari",
            },
        ),
    ]
