# Generated by Django 5.2.7 on 2026-02-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_programstatictexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstatictexts',
            name='title_en',
            field=models.CharField(default="Ta'lim dasturlari", max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='programstatictexts',
            name='title_ru',
            field=models.CharField(default="Ta'lim dasturlari", max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='programstatictexts',
            name='title_uz',
            field=models.CharField(default="Ta'lim dasturlari", max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
