# Generated by Django 5.2.7 on 2026-02-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_programstatictexts_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLifeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Rasm')),
                ('image_alt_uz', models.CharField(blank=True, max_length=255, verbose_name="Rasm alt (O'zbekcha)")),
                ('image_alt_ru', models.CharField(blank=True, max_length=255, verbose_name='Rasm alt (Ruscha)')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='Rasm alt (Inglizcha)')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('link', models.CharField(default='#', max_length=255, verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': '8. Talabalar hayoti elementi',
                'verbose_name_plural': '8. Talabalar hayoti elementlari',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentLifeStaticTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(default='Talabalar Hayoti', max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(default='Talabalar Hayoti', max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(default='Talabalar Hayoti', max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(default='Talabalar Hayoti', max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_highlight', models.CharField(default='Hayoti', max_length=100, verbose_name="Ajratilgan so'z (<span>)")),
                ('title_highlight_uz', models.CharField(default='Hayoti', max_length=100, null=True, verbose_name="Ajratilgan so'z (<span>)")),
                ('title_highlight_ru', models.CharField(default='Hayoti', max_length=100, null=True, verbose_name="Ajratilgan so'z (<span>)")),
                ('title_highlight_en', models.CharField(default='Hayoti', max_length=100, null=True, verbose_name="Ajratilgan so'z (<span>)")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': '8. Talabalar hayoti statik matnlari',
                'verbose_name_plural': '8. Talabalar hayoti statik matnlari',
            },
        ),
    ]
