# Generated by Django 5.2.7 on 2026-02-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_studentlifeitem_studentlifestatictexts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionStaticTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(default="Ta'lim yo'nalishlari", max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(default="Ta'lim yo'nalishlari", max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(default="Ta'lim yo'nalishlari", max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(default="Ta'lim yo'nalishlari", max_length=255, null=True, verbose_name='Sarlavha')),
                ('button_text', models.CharField(default="Ko'proq yuklash", max_length=100, verbose_name='Tugma matni')),
                ('button_text_uz', models.CharField(default="Ko'proq yuklash", max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_text_ru', models.CharField(default="Ko'proq yuklash", max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_text_en', models.CharField(default="Ko'proq yuklash", max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='/programs/', max_length=255, verbose_name='Tugma havolasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': "9. Yo'nalishlar statik matnlari",
                'verbose_name_plural': "9. Yo'nalishlar statik matnlari",
            },
        ),
    ]
