# Generated by Django 5.2.7 on 2026-02-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_directionstatictexts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStaticTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(default='Yaqinlashib kelayotgan tadbirlar', max_length=255, verbose_name='Sarlavha')),
                ('button_text', models.CharField(default="Barchasini ko'rish", max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='/events/', max_length=255, verbose_name='Tugma havolasi')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='home/events/', verbose_name='Yon tarafdagi rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': '10. Tadbirlar statik matnlari',
                'verbose_name_plural': '10. Tadbirlar statik matnlari',
            },
        ),
    ]
