# Generated by Django 5.2.7 on 2026-02-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_eventstatictexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatictexts',
            name='button_text_en',
            field=models.CharField(default="Barchasini ko'rish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='eventstatictexts',
            name='button_text_ru',
            field=models.CharField(default="Barchasini ko'rish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='eventstatictexts',
            name='button_text_uz',
            field=models.CharField(default="Barchasini ko'rish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='eventstatictexts',
            name='title_en',
            field=models.CharField(default='Yaqinlashib kelayotgan tadbirlar', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='eventstatictexts',
            name='title_ru',
            field=models.CharField(default='Yaqinlashib kelayotgan tadbirlar', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='eventstatictexts',
            name='title_uz',
            field=models.CharField(default='Yaqinlashib kelayotgan tadbirlar', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
