# Generated by Django 5.2.7 on 2026-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_eventstatictexts_button_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipStaticTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(default='Universitet Rahbariyati', max_length=255, verbose_name='Sarlavha')),
                ('button_text', models.CharField(default='Batafsil', max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='/about/leadership/', max_length=255, verbose_name='Tugma havolasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': '11. Rahbariyat statik matnlari',
                'verbose_name_plural': '11. Rahbariyat statik matnlari',
            },
        ),
    ]
