# Generated by Django 5.2.7 on 2026-02-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_leadershipstatictexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipstatictexts',
            name='button_text_en',
            field=models.CharField(default='Batafsil', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='leadershipstatictexts',
            name='button_text_ru',
            field=models.CharField(default='Batafsil', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='leadershipstatictexts',
            name='button_text_uz',
            field=models.CharField(default='Batafsil', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='leadershipstatictexts',
            name='title_en',
            field=models.CharField(default='Universitet Rahbariyati', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='leadershipstatictexts',
            name='title_ru',
            field=models.CharField(default='Universitet Rahbariyati', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='leadershipstatictexts',
            name='title_uz',
            field=models.CharField(default='Universitet Rahbariyati', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
