# Generated by Django 5.2.7 on 2026-02-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_leadershipstatictexts_button_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(default="2024-2025 o'quv yili uchun qabul boshlandi", max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('background_image', models.ImageField(upload_to='home/admission/', verbose_name='Fon rasmi')),
                ('button_text', models.CharField(default='Ariza topshirish', max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='/admissions/', max_length=255, verbose_name='Tugma havolasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': '12. Qabul banner',
                'verbose_name_plural': '12. Qabul banner',
            },
        ),
    ]
