# Generated by Django 5.2.7 on 2026-02-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_admissionbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionbanner',
            name='button_text_en',
            field=models.CharField(default='Ariza topshirish', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='admissionbanner',
            name='button_text_ru',
            field=models.CharField(default='Ariza topshirish', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='admissionbanner',
            name='button_text_uz',
            field=models.CharField(default='Ariza topshirish', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='admissionbanner',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='admissionbanner',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='admissionbanner',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='admissionbanner',
            name='title_en',
            field=models.CharField(default="2024-2025 o'quv yili uchun qabul boshlandi", max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='admissionbanner',
            name='title_ru',
            field=models.CharField(default="2024-2025 o'quv yili uchun qabul boshlandi", max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='admissionbanner',
            name='title_uz',
            field=models.CharField(default="2024-2025 o'quv yili uchun qabul boshlandi", max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
