# Generated by Django 5.2.7 on 2026-02-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_admissionbanner_button_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(default='Grantlar va Moliyaviy yordam', max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(default='Grantlar va Moliyaviy yordam', max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(default='Grantlar va Moliyaviy yordam', max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(default='Grantlar va Moliyaviy yordam', max_length=255, null=True, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('button_text', models.CharField(default='Batafsil', max_length=100, verbose_name='Tugma matni')),
                ('button_text_uz', models.CharField(default='Batafsil', max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_text_ru', models.CharField(default='Batafsil', max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_text_en', models.CharField(default='Batafsil', max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='/scholarships/', max_length=255, verbose_name='Tugma havolasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': '13. Grantlar banner',
                'verbose_name_plural': '13. Grantlar banner',
            },
        ),
    ]
