# Generated by Django 5.2.7 on 2026-02-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_scholarshipbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryStaticTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(default='Fotogalereya', max_length=255, verbose_name='Sarlavha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': '14. Galereya statik matnlari',
                'verbose_name_plural': '14. Galereya statik matnlari',
            },
        ),
    ]
