# Generated by Django 5.2.7 on 2026-02-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_gallerystatictexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerystatictexts',
            name='title_en',
            field=models.CharField(default='Fotogalereya', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='gallerystatictexts',
            name='title_ru',
            field=models.CharField(default='Fotogalereya', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='gallerystatictexts',
            name='title_uz',
            field=models.CharField(default='Fotogalereya', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
