# Generated by Django 5.2.7 on 2026-02-01 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCategoryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Footer kategoriya menu',
                'verbose_name_plural': 'Footer kategoriya menyular',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('about_title', models.CharField(blank=True, max_length=255, verbose_name='Haqida sarlavhasi')),
                ('about_text', models.TextField(blank=True, verbose_name='Haqida matni')),
                ('show_newsletter', models.BooleanField(default=True, verbose_name="Newsletter ko'rsatish")),
                ('newsletter_title', models.CharField(blank=True, max_length=255, verbose_name='Newsletter sarlavhasi')),
                ('newsletter_description', models.TextField(blank=True, verbose_name='Newsletter tavsifi')),
                ('show_recent_news', models.BooleanField(default=True, verbose_name="So'nggi yangiliklar ko'rsatish")),
                ('recent_news_count', models.PositiveIntegerField(default=2, verbose_name="So'nggi yangiliklar soni")),
                ('show_copyright', models.BooleanField(default=True, verbose_name="Copyright ko'rsatish")),
                ('show_payment_icons', models.BooleanField(default=False, verbose_name="To'lov tizimlarini ko'rsatish")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Footer sozlamasi',
                'verbose_name_plural': 'Footer sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('banner_text', models.CharField(blank=True, max_length=255, verbose_name='Banner matni')),
                ('banner_link', models.URLField(blank=True, verbose_name='Banner havolasi')),
                ('show_banner', models.BooleanField(default=False, verbose_name="Bannerni ko'rsatish")),
                ('show_header_button', models.BooleanField(default=True, verbose_name="Header tugmasini ko'rsatish")),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.URLField(blank=True, verbose_name='Tugma havolasi')),
                ('show_search', models.BooleanField(default=True, verbose_name="Qidiruvni ko'rsatish")),
                ('show_language_switcher', models.BooleanField(default=True, verbose_name="Til almashtirgichni ko'rsatish")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Header sozlamasi',
                'verbose_name_plural': 'Header sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('site_name', models.CharField(max_length=255, verbose_name='Sayt nomi')),
                ('site_description', models.TextField(verbose_name='Sayt tavsifi')),
                ('site_keywords', models.TextField(blank=True, verbose_name="Kalit so'zlar")),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Asosiy logo')),
                ('logo_white', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Oq logo')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Qora logo')),
                ('favicon', models.ImageField(upload_to='logos/', verbose_name='Favicon')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='Telefon 2')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('email_2', models.EmailField(blank=True, max_length=254, verbose_name='Email 2')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('work_time', models.CharField(blank=True, max_length=255, verbose_name='Ish vaqti')),
                ('map_iframe', models.TextField(blank=True, verbose_name='Google Maps iframe')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik')),
                ('copyright_text', models.CharField(blank=True, max_length=255, verbose_name='Copyright matni')),
                ('google_analytics', models.TextField(blank=True, verbose_name='Google Analytics kodi')),
                ('yandex_metrika', models.TextField(blank=True, verbose_name='Yandex Metrika kodi')),
                ('facebook_pixel', models.TextField(blank=True, verbose_name='Facebook Pixel kodi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Sayt sozlamasi',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('url', models.URLField(verbose_name='Havola')),
                ('icon', models.CharField(max_length=100, verbose_name='Icon class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FooterMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon class')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='Yangi oynada ochish')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='settings.footercategorymenu', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Footer menu elementi',
                'verbose_name_plural': 'Footer menu elementlari',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HeaderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL / Havola')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon class')),
                ('is_mega_menu', models.BooleanField(default=False, verbose_name='Mega menu')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif (Mega menu uchun)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Rasm (Mega menu uchun)')),
                ('show_badge', models.BooleanField(default=False, verbose_name="Badge ko'rsatish")),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='Badge matni')),
                ('badge_color', models.CharField(default='#FF0000', max_length=7, verbose_name='Badge rangi')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='Yangi oynada ochish')),
                ('css_class', models.CharField(blank=True, max_length=100, verbose_name='CSS class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='settings.headermenu', verbose_name='Asosiy menyu')),
            ],
            options={
                'verbose_name': 'Header menyu',
                'verbose_name_plural': 'Header menyular',
                'ordering': ['order', 'title'],
            },
        ),
    ]
