# Generated by Django 5.2.7 on 2026-02-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercategorymenu',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='footercategorymenu',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='footercategorymenu',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='footermenuitem',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='footermenuitem',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='footermenuitem',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='about_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Haqida matni'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='about_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Haqida matni'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='about_text_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Haqida matni'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='about_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Haqida sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='about_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Haqida sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='about_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Haqida sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Newsletter tavsifi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Newsletter tavsifi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Newsletter tavsifi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Newsletter sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Newsletter sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Newsletter sarlavhasi'),
        ),
        migrations.AddField(
            model_name='headermenu',
            name='badge_text_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge matni'),
        ),
        migrations.AddField(
            model_name='headermenu',
            name='badge_text_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge matni'),
        ),
        migrations.AddField(
            model_name='headermenu',
            name='badge_text_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge matni'),
        ),
        migrations.AddField(
            model_name='headermenu',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (Mega menu uchun)'),
        ),
        migrations.AddField(
            model_name='headermenu',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (Mega menu uchun)'),
        ),
        migrations.AddField(
            model_name='headermenu',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (Mega menu uchun)'),
        ),
        migrations.AddField(
            model_name='headermenu',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='headermenu',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='headermenu',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='banner_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner matni'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='banner_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner matni'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='banner_text_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner matni'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_text_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_uz',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Copyright matni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Copyright matni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Copyright matni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_en',
            field=models.TextField(null=True, verbose_name='Sayt tavsifi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_ru',
            field=models.TextField(null=True, verbose_name='Sayt tavsifi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_uz',
            field=models.TextField(null=True, verbose_name='Sayt tavsifi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name="Kalit so'zlar"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Kalit so'zlar"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_keywords_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Kalit so'zlar"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sayt nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sayt nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sayt nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_time_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_time_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_time_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ish vaqti'),
        ),
    ]
