# Generated by Django 5.2.7 on 2026-02-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_footercategorymenu_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(upload_to='logos/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(upload_to='logos/', verbose_name='Asosiy logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_dark',
            field=models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='Qora logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_white',
            field=models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='Oq logo'),
        ),
    ]
