# Generated by Django 5.2.7 on 2026-02-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_sitesettings_favicon_alter_sitesettings_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersettings',
            name='banner_link',
            field=models.CharField(blank=True, verbose_name='Banner havolasi'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='button_link',
            field=models.CharField(blank=True, verbose_name='Tugma havolasi'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='url',
            field=models.CharField(verbose_name='Havola'),
        ),
    ]
