# Generated by Django 5.2.7 on 2026-02-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_headersettings_banner_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_2',
            field=models.CharField(blank=True, max_length=25, verbose_name='Telefon 2'),
        ),
    ]
