# Generated by Django 5.2.7 on 2026-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_sitesettings_phone_alter_sitesettings_phone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, verbose_name='Uzunlik'),
        ),
    ]
