# Generated by Django 5.2.7 on 2026-02-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_sitesettings_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='button_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner rasmi'),
        ),
    ]
