# Generated by Django 5.2.7 on 2026-02-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_headersettings_button_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_description',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_description_en',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_description_ru',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_description_uz',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_title',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_title_en',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_title_ru',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_title_uz',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='show_newsletter',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='show_payment_icons',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_label',
            field=models.CharField(default='Barcha huquqlar himoyalangan', max_length=200, verbose_name='Copyright matni'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_label_en',
            field=models.CharField(default='Barcha huquqlar himoyalangan', max_length=200, null=True, verbose_name='Copyright matni'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_label_ru',
            field=models.CharField(default='Barcha huquqlar himoyalangan', max_length=200, null=True, verbose_name='Copyright matni'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_label_uz',
            field=models.CharField(default='Barcha huquqlar himoyalangan', max_length=200, null=True, verbose_name='Copyright matni'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='recent_news_title',
            field=models.CharField(default="So'nggi yangiliklar", max_length=100, verbose_name='Yangiliklar sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='recent_news_title_en',
            field=models.CharField(default="So'nggi yangiliklar", max_length=100, null=True, verbose_name='Yangiliklar sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='recent_news_title_ru',
            field=models.CharField(default="So'nggi yangiliklar", max_length=100, null=True, verbose_name='Yangiliklar sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='recent_news_title_uz',
            field=models.CharField(default="So'nggi yangiliklar", max_length=100, null=True, verbose_name='Yangiliklar sarlavhasi'),
        ),
    ]
