# Generated by Django 5.2.7 on 2026-02-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Rasm')),
                ('image_large', models.ImageField(blank=True, null=True, upload_to='gallery/large/', verbose_name='Katta rasm (lightbox)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Bosh sahifada ko'rsatish")),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
