# Generated by Django 5.2.7 on 2026-02-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyBreadcrumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name="Qo'shimcha sarlavha")),
                ('subtitle_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name="Qo'shimcha sarlavha")),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name="Qo'shimcha sarlavha")),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True, verbose_name="Qo'shimcha sarlavha")),
                ('parent_title', models.CharField(default='Bosh sahifa', max_length=100, verbose_name='Ota sahifa nomi')),
                ('parent_title_uz', models.CharField(default='Bosh sahifa', max_length=100, null=True, verbose_name='Ota sahifa nomi')),
                ('parent_title_ru', models.CharField(default='Bosh sahifa', max_length=100, null=True, verbose_name='Ota sahifa nomi')),
                ('parent_title_en', models.CharField(default='Bosh sahifa', max_length=100, null=True, verbose_name='Ota sahifa nomi')),
                ('parent_link', models.CharField(default='/', max_length=255, verbose_name='Ota sahifa havolasi')),
                ('background_image', models.ImageField(upload_to='faculties/breadcrumb/', verbose_name='Fon rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Breadcrumb',
                'verbose_name_plural': 'Breadcrumb',
            },
        ),
    ]
