# Generated by Django 5.2.7 on 2026-02-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0003_divisionbreadcrumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='dean_message',
            field=models.TextField(blank=True, verbose_name='Dekan xabari'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean_message_en',
            field=models.TextField(blank=True, null=True, verbose_name='Dekan xabari'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean_message_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Dekan xabari'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean_message_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dekan xabari sarlavhasi'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean_message_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dekan xabari sarlavhasi'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean_message_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dekan xabari sarlavhasi'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean_message_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dekan xabari sarlavhasi'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean_message_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Dekan xabari'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='mission',
            field=models.TextField(blank=True, verbose_name='Missiya'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='mission_en',
            field=models.TextField(blank=True, null=True, verbose_name='Missiya'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='mission_image',
            field=models.ImageField(blank=True, null=True, upload_to='faculties/mission/', verbose_name='Missiya rasmi'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='mission_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Missiya'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='mission_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Missiya'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='vision',
            field=models.TextField(blank=True, verbose_name='Viziya'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='vision_en',
            field=models.TextField(blank=True, null=True, verbose_name='Viziya'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='vision_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Viziya'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='vision_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Viziya'),
        ),
    ]
