# Generated by Django 5.2.7 on 2026-02-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0004_faculty_dean_message_faculty_dean_message_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_address_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_address_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_address_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_rank',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ilmiy unvon'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_rank_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy unvon'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_rank_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy unvon'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_rank_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy unvon'),
        ),
        migrations.AddField(
            model_name='department',
            name='international_cooperation',
            field=models.TextField(blank=True, verbose_name='Xalqaro hamkorlik'),
        ),
        migrations.AddField(
            model_name='department',
            name='international_cooperation_en',
            field=models.TextField(blank=True, null=True, verbose_name='Xalqaro hamkorlik'),
        ),
        migrations.AddField(
            model_name='department',
            name='international_cooperation_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Xalqaro hamkorlik'),
        ),
        migrations.AddField(
            model_name='department',
            name='international_cooperation_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Xalqaro hamkorlik'),
        ),
        migrations.AddField(
            model_name='department',
            name='scientific_activity',
            field=models.TextField(blank=True, verbose_name='Ilmiy faoliyat'),
        ),
        migrations.AddField(
            model_name='department',
            name='scientific_activity_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ilmiy faoliyat'),
        ),
        migrations.AddField(
            model_name='department',
            name='scientific_activity_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ilmiy faoliyat'),
        ),
        migrations.AddField(
            model_name='department',
            name='scientific_activity_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Ilmiy faoliyat'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='Kafedra tarixi'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kafedra tarixi'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Kafedra tarixi'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Kafedra tarixi'),
        ),
    ]
