# Generated by Django 5.2.7 on 2026-02-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0005_department_head_address_department_head_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='dean_message_label',
            field=models.CharField(default='Dekan xabari', max_length=100, verbose_name="'Dekan xabari' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='dean_message_label_en',
            field=models.CharField(default='Dekan xabari', max_length=100, null=True, verbose_name="'Dekan xabari' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='dean_message_label_ru',
            field=models.CharField(default='Dekan xabari', max_length=100, null=True, verbose_name="'Dekan xabari' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='dean_message_label_uz',
            field=models.CharField(default='Dekan xabari', max_length=100, null=True, verbose_name="'Dekan xabari' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='departments_label',
            field=models.CharField(default="Kafedralar ro'yxati", max_length=100, verbose_name="'Kafedralar ro'yxati' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='departments_label_en',
            field=models.CharField(default="Kafedralar ro'yxati", max_length=100, null=True, verbose_name="'Kafedralar ro'yxati' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='departments_label_ru',
            field=models.CharField(default="Kafedralar ro'yxati", max_length=100, null=True, verbose_name="'Kafedralar ro'yxati' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='departments_label_uz',
            field=models.CharField(default="Kafedralar ro'yxati", max_length=100, null=True, verbose_name="'Kafedralar ro'yxati' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='mission_label',
            field=models.CharField(default='Missiya', max_length=100, verbose_name="'Missiya' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='mission_label_en',
            field=models.CharField(default='Missiya', max_length=100, null=True, verbose_name="'Missiya' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='mission_label_ru',
            field=models.CharField(default='Missiya', max_length=100, null=True, verbose_name="'Missiya' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='mission_label_uz',
            field=models.CharField(default='Missiya', max_length=100, null=True, verbose_name="'Missiya' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='vision_label',
            field=models.CharField(default='Viziya', max_length=100, verbose_name="'Viziya' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='vision_label_en',
            field=models.CharField(default='Viziya', max_length=100, null=True, verbose_name="'Viziya' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='vision_label_ru',
            field=models.CharField(default='Viziya', max_length=100, null=True, verbose_name="'Viziya' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='facultybreadcrumb',
            name='vision_label_uz',
            field=models.CharField(default='Viziya', max_length=100, null=True, verbose_name="'Viziya' sarlavhasi"),
        ),
    ]
