# Generated by Django 5.2.7 on 2026-02-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0007_departmentbreadcrumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentbreadcrumb',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
    ]
